let catalogo=[
//TODO ROLLER
{
    id:1,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/CORTINAS%20ROLLER/Cortina%20(1).png',
    tipo:'roller',
    url:'https://drive.google.com/file/d/1Yl92DJcGW2y6Ikn__NexHcxgpaFFRyAA/view?usp=drive_link'
},
{
    id:2,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/CORTINAS%20ROLLER/Cortina%20(2).png',
    tipo:'roller',
    url:'https://drive.google.com/file/d/1R7UgJE1Vtslh4I4nWO4geQf7vlj91nLJ/view?usp=drive_link'
},
{
    id:3,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/CORTINAS%20ROLLER/Cortina%20(3).png',
    tipo:'roller',
    url:'https://drive.google.com/file/d/19pzzS-C6L9QFBzBf2vBYh8gK7baF97mC/view?usp=drive_link'
},
{
    id:4,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/CORTINAS%20ROLLER/Cortina%20(4).png',
    tipo:'roller',
    url:'https://drive.google.com/file/d/1z93cZ9MdYiRYb7AcI3wgYVMIXVcdeTWF/view?usp=drive_link'
},
{
    id:5,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/CORTINAS%20ROLLER/Cortina%20(5).png',
    tipo:'roller',
    url:'https://drive.google.com/file/d/1Vxcjhe7fYt4dpMLUofXuFWGJ7477APMB/view?usp=drive_link'
},
//TODO PUERTAS
{
    id:6,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PUERTAS/Puerta%20(1).png',
    tipo:'puertas',
    url:'https://drive.google.com/file/d/1YblOyWTbPyzRMVmVWFCqzXwCym_2S4Kt/view?usp=drive_link'
},
{
    id:7,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PUERTAS/Puerta%20(2).png',
    tipo:'puertas',
    url:'https://drive.google.com/file/d/1aCKyMlP9vDcceY9fR1_DQNwXoX461aXa/view?usp=drive_link'
},
{
    id:8,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PUERTAS/Puerta%20(3).png',
    tipo:'puertas',
    url:'https://drive.google.com/file/d/1DeuEvb54mnWW_F-RSMRlLRn97IvIfR-n/view?usp=drive_link'
},
{
    id:9,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PUERTAS/Puerta%20(4).png',
    tipo:'puertas',
    url:'https://drive.google.com/file/d/1-4fPouGphc-N97RUg_fBrNMpP2rj2NDU/view?usp=drive_link'
},
{
    id:10,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PUERTAS/Puerta%20(5).png',
    tipo:'puertas',
    url:'https://drive.google.com/file/d/13FJHZcEMN6gQQ7rFnJP9BbFwuZy15Y_q/view?usp=drive_link'
},
{
    id:11,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PUERTAS/Puerta%20(6).png',
    tipo:'puertas',
    url:'https://drive.google.com/file/d/1XI60Ki7mU2SN2hERr357EWE9yNz6A0pA/view?usp=drive_link'
},
//TODO MAMPARAS
{
    id:12,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(1).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1QP26hXjPoCzmSi-BIWAuGJkdmXrpWW8o/view?usp=drive_link'
},
{
    id:13,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(2).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1NrR8FKUD3U13AvRBPO92Z0K9SzXFaIdE/view?usp=drive_link'
},
{
    id:14,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(3).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1BIvnPvOrvxcLYsJYV5CQZ0y_Coj_h9tV/view?usp=drive_link'
},
{
    id:15,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(4).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1fxnxEyOphQqN1aQ5CqgYx3saT0fSFerG/view?usp=drive_link'
},
{
    id:16,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(5).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/15YfWZYhKs1HEeAZnv7LN37nexwNWHD1Z/view?usp=drive_link'
},
{
    id:17,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(6).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1BqZJQAAHiFT6JyI0FnR48XqN6PlQ75yd/view?usp=drive_link'
},
{
    id:18,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(7).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1sFQzOVQT4m1Ey_Cu23plL8fxJVU8vbKK/view?usp=drive_link'
},
{
    id:19,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(8).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1mo1bEqhee_YW-iy15iiJUNyBHoP5SK92/view?usp=drive_link'
},
{
    id:20,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(9).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/1fDVh1P_91VIarBNtzOH8n1wd8E_m-kqg/view?usp=drive_link'
},
{
    id:21,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MAMPARAS/Mampara%20(10).png',
    tipo:'mamparas',
    url:'https://drive.google.com/file/d/15joRffnklN5KJoz7FS2F8ZX_OBfq7eMS/view?usp=drive_link'
},

{
    id:22,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MOSQUITEROS/Mosquitero%20(1).png',
    tipo:'mosquiteros',
    url:'https://drive.google.com/file/d/1qHp_WIgQMOomz0HPsOhe2QbB8DbrU_z8/view?usp=drive_link'
},
{
    id:23,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MOSQUITEROS/Mosquitero%20(2).png',
    tipo:'mosquiteros',
    url:'https://drive.google.com/file/d/1qYYiVfyHYzZ7DsFhGIUqC0dl2hZe4SE3/view?usp=drive_link'
},
{
    id:24,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MOSQUITEROS/Mosquitero%20(3).png',
    tipo:'mosquiteros',
    url:'https://drive.google.com/file/d/1gqq06orJhSNco_6vTqfDqGTdHZ-dNZZP/view?usp=drive_link'
},
{
    id:25,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MOSQUITEROS/Mosquitero%20(4).png',
    tipo:'mosquiteros',
    url:'https://drive.google.com/file/d/1G_y34KfQW9_U9WoSSkVm7hlK9yH9GOrQ/view?usp=drive_link'
},
{
    id:26,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/MOSQUITEROS/Mosquitero%20(5).png',
    tipo:'mosquiteros',
    url:'https://drive.google.com/file/d/1jQDwglKD06QnRn2yX4O6_tjHM98oHsQe/view?usp=drive_link'
},
{
    id:27,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(1).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/16tZrCVJOWCgdnua_5us1qkDTLTs767Hw/view?usp=drive_link'
},
{
    id:28,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(2).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1JwluBJgYkiDuDpGzlpinP6myIsJ9muR0/view?usp=drive_link'
},
{
    id:29,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(3).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1J88AIFk7K7IxGdeKf8IO105oYNVjFO4a/view?usp=drive_link'
},
{
    id:30,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(4).pngg',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1S1Erh7-JdCCrxd9Rfzab8A1_Tq-pa1ob/view?usp=drive_link'
},
{
    id:31,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(5).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1kVdZ1qjBY8iSGncVcelLICbtrc67WzLw/view?usp=drive_link'
},
{
    id:32,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(6).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1TSlUxXddPbSoA5ExJNOdm0sSuUqc0u0y/view?usp=drive_link'
},
{
    id:33,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(7).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1Axi2ADFFyaRifDFKUTV5Isk7dCauB9RB/view?usp=drive_link'
},
{
    id:34,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(8).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/14FLYylhtkGo-EZnuKitS64aVavGQ7ubt/view?usp=drive_link'
},
{
    id:35,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(9).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1ytuIvl7I_-C7HeBhv3s0pVFZzdTqh0cE/view?usp=drive_link'
},
{
    id:36,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(10).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/13UOgmCVtCyCZuA0dBc3rMLLu4z1iij29/view?usp=drive_link'
},
{
    id:37,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(11).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1sIzGQCn8L-BMQgQggXgCW4cjcizVMi6_/view?usp=drive_link'
},
{
    id:38,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(12).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1NClkPMWi0MCOPxI2q0XJNm0rbX6op_o9/view?usp=drive_link'
},
{
    id:39,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(13).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1OjOw7-_XHlffKtzUhkUYTuvAJLDLm_6N/view?usp=drive_link'
},
{
    id:40,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(14).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1KaG-7p2tzORXPnoIPhsM_YezLAMr9_yU/view?usp=drive_link'
},
{
    id:41,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/PERSIANAS/Persiana%20(15).png',
    tipo:'persianas',
    url:'https://drive.google.com/file/d/1lroxezXjw8ITzbWJscjmnfR-uxynkfiH/view?usp=drive_link'
},

{
    id:42,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(1).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1ehGf7RyJyhJWGIVZOOTTk-hkb6uXv4DC/view?usp=drive_link'
},
{
    id:43,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(2).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1VwxDpi4sHfqfvDAjukGakMQnsoHq-gZ0/view?usp=drive_link'
},
{
    id:44,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(3).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1_nvu0V32CObBQonms9C9jhypS1KTKCDT/view?usp=drive_link'
},
{
    id:45,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(4).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1Udla4dOG-kA1t30te7FAbQU89f8bvyF6/view?usp=drive_link'
},
{
    id:46,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(5).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1hg29l7S4XPIFatkwIwNivr8jreqf2y6a/view?usp=drive_link'
},
{
    id:47,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(6).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1gFxvy4-AUQG2qWzpsaBTPrEad6FBYol6/view?usp=drive_link'
},
{
    id:48,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(7).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1VguU0KNEU4VyKuV2N6NFL_BCDodsP-2X/view?usp=drive_link'
},
{
    id:49,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(8).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1JHZEOE68ptlcuIH85qMGxKba2-mq8B2d/view?usp=drive_link'
},
{
    id:50,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(9).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/10quimwrI3q9X2H8oILeRemTETMfJyVw4/view?usp=drive_link'
},
{
    id:51,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(10).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/10cQ6wSvQSmJ6sWauq8eVFp46P7s-2Kwh/view?usp=drive_link'
},
{
    id:52,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(11).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1DPuaMC8DcP0a2wJRTRCKJZ_17xI_HjPv/view?usp=drive_link'
},
{
    id:53,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(12).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1ct7dszHZHExAf0Wyt9wgy-8OtumBJD3G/view?usp=drive_link'
},
{
    id:54,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(13).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1OKXhg12gwSalBsHB7kYI-I5aQpCLDCQs/view?usp=drive_link'
},
{
    id:55,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(14).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1nQ6LAsq7HtlnNH3aHzZn3jF_RJsQ-K1q/view?usp=drive_link'
},
{
    id:56,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(15).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1HPDJvlo6rbhqzzIQ8DC0eQ_eCXLLMRDq/view?usp=drive_link'
},
{
    id:57,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(16).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1eaJz6GWy0QHwZBSSYcZ-j3E0vOaRdXC5/view?usp=drive_link'
},
{
    id:58,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventana%20(17).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1qk8V9obuJXmJMe2PvdYow0_2UGH7RK0w/view?usp=drive_link'
},
{
    id:59,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(1).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1V4qCSrDbXkxNiBoFsis7x_5jiAn4xVEo/view?usp=drive_link'
},
{
    id:60,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(2).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1WxinlmUw5qJCoveLx6BMXMvv13bMtclV/view?usp=drive_link'
},
{
    id:73,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(3).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1acqo_fIop9US3xaYGbfXlyiBP7jiINi5/view?usp=drive_link'
},
{
    id:61,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(4).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1w1jJvTUZq3iF1pGnqp1utpnUxtBVcltI/view?usp=drive_link'
},
{
    id:62,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(5).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1v4RKzgOF53UlD801STFLru_ocGLGU8wK/view?usp=drive_link'
},
{
    id:63,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(6).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1bgVk6_oDCt_Hprn1B9vA-xQhHjwPFCLd/view?usp=drive_link'
},
{
    id:64,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(7).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1Fb7J-gC4GmCnUIzSpNB0F_r1_KA6SosZ/view?usp=drive_link'
},
{
    id:65,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(8).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1iU3RF-1bHqWGgkR6SbFovgp6fM5m-sfM/view?usp=drive_link'
},
{
    id:66,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(9).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1KHmMKuh8PzfmxX5-A9G_268hySvHJTQw/view?usp=drive_link'
},
{
    id:67,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(10).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1CRw6fVga0JN1bVrEO0eecFv23YQaF7lb/view?usp=drive_link'
},
{
    id:68,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(11).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1JfwkyC1yHDYp978xikiTQyAvMKB21_g0/view?usp=drive_link'
},
{
    id:69,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(12).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/10T8ueKfKTjVzUlOUr_-woVzrZBhIvcCi/view?usp=drive_link'
},
{
    id:70,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(13).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1ZayTSXsZHbY7qQDrnB_d7GgrrE5UIUUp/view?usp=drive_link'
},
{
    id:71,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(14).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1OuP_F21jzaE2X3Jp51fxhvSOzzcYiMsQ/view?usp=drive_link'
},
{
    id:72,        
    image:'https://ixslflqbxuycaremgpki.supabase.co/storage/v1/object/public/catalogo/catalogo/VENTANAS%20&%20VENTANALES/Ventanal%20(15).png',
    tipo:'ventanas',
    url:'https://drive.google.com/file/d/1zSPQW1K591QqmYzDDUWx8WonzLTtREUU/view?usp=drive_link'
},
]
export default catalogo